[package]
name = "nape_testing_assertions"
version = "1.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nape_kernel = { path = "../../kernel" }