[package]
name = "nape_domain"
version = "1.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = []

[dependencies]
kernel_oss = { path = "../../../kernel/kernel-oss" }

[dev-dependencies]
test_framework_oss = { path = "../../../test-framework/test-framework-oss" }
