[package]
name = "nape_domain"
version = "1.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = []
medium_tests = []

[dependencies]
kernel_oss = { git = "https://github.com/attestify/kernel-oss.git", tag="0.2.4" }

[dev-dependencies]
test_framework_oss = { git = "https://github.com/attestify/test-framework-oss.git", tag = "0.2.4", features = ["nape_filesystem"] }
