name: NAPE - Continuous Integration (CI) Workflow

on:
  pull_request:

permissions:
  contents: write
  id-token: write

jobs:
  source-code-integration:
    uses: nape-not-another-policy-engine/nape-build-deploy-release/.github/workflows/rust-standard-ci-workflow.yaml@main
    secrets: inherit
