name: NAPE Repo - Continuous Integration (CI) Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  source-code-integration:
    uses: nape-not-another-policy-engine/nape-build-deploy-release/.github/workflows/nape-integration.yml@main